import { COLOR, RGB } from './color';

export const COLORS = {
    // Common Gradients
    BW: [COLOR.BLACK, COLOR.WHITE] as RGB[],
    WB: [COLOR.WHITE, COLOR.BLACK] as RGB[],
    RGB: [COLOR.RED, COLOR.GREEN, COLOR.BLUE] as RGB[],
    HOT_METAL: [COLOR.BLACK, COLOR.DARKRED, COLOR.RED, COLOR.ORANGE, COLOR.YELLOW, COLOR.WHITE] as RGB[],
    RAINBOW: [COLOR.PURPLE, COLOR.BLUE, COLOR.CYAN, COLOR.GREEN, COLOR.YELLOW, COLOR.RED] as RGB[],
    OCEAN: [COLOR.NAVY, COLOR.TEAL, COLOR.CORNFLOWERBLUE, COLOR.LIGHTSEAGREEN, COLOR.AQUA] as RGB[],
    FIRE: [COLOR.BLACK, COLOR.DARKRED, COLOR.ORANGE, COLOR.YELLOW, COLOR.WHITE] as RGB[],
    PURPLE_HAZE: [COLOR.INDIGO, COLOR.PURPLE, COLOR.DEEPPINK, COLOR.LAVENDER, COLOR.WHITE] as RGB[],
    GREYSCALE: [COLOR.BLACK, COLOR.DIMGRAY, COLOR.GRAY, COLOR.LIGHTGREY, COLOR.WHITE] as RGB[],
    SUNSET: [COLOR.DARKBLUE, COLOR.ORANGE, COLOR.SALMON, COLOR.GOLD, COLOR.YELLOW] as RGB[],
    ELECTRIC: [COLOR.INDIGO, COLOR.DODGERBLUE, COLOR.CYAN, COLOR.LIMEGREEN] as RGB[],
    PASTEL: [COLOR.LAVENDER, COLOR.MINTGREEN, COLOR.SKYBLUE, COLOR.THISTLE] as RGB[],
    CAPPUCCINO: [COLOR.WARM_MILK, COLOR.MILKY_COFFEE, COLOR.COFFEE_BROWN, COLOR.DARK_ESPRESSO, COLOR.FOAM_WHITE] as RGB[],

    // C64 inspired
    C64_RAINBOW: [COLOR.C64_BLUE, COLOR.C64_PURPLE, COLOR.C64_RED, COLOR.C64_YELLOW, COLOR.C64_GREEN] as RGB[],
    C64_MANDELBROT: [COLOR.C64_BLACK, COLOR.C64_BLUE, COLOR.C64_LIGHT_BLUE, COLOR.C64_PURPLE, COLOR.C64_RED, COLOR.C64_LIGHT_RED, COLOR.C64_ORANGE, COLOR.YELLOW, COLOR.C64_WHITE] as RGB[],
    C64_ALL_COLORS: [COLOR.C64_BLACK, COLOR.C64_RED, COLOR.C64_CYAN, COLOR.C64_PURPLE, COLOR.C64_GREEN, COLOR.C64_BLUE, COLOR.C64_YELLOW, COLOR.C64_ORANGE, COLOR.C64_BROWN, COLOR.C64_LIGHT_RED, COLOR.C64_DARK_GREY, COLOR.C64_GREY, COLOR.C64_LIGHT_GREEN, COLOR.C64_LIGHT_BLUE, COLOR.C64_LIGHT_GREY, COLOR.C64_WHITE] as RGB[],
};
