export enum CalculationType {
    ITERATIONS = 'ITERATIONS',
    ITERATIONS_PT = 'ITERATIONS_PT',
    ITERATIONS_SMOOTH = 'ITERATIONS_SMOOTH',
    ITERATIONS_SMOOTH_PT = 'ITERATIONS_SMOOTH_PT',
    DISTANCE = 'DISTANCE',
    DISTANCE_PT = 'DISTANCE_PT',
}
